### ISSUE TITLE
Some neighbor entries are not configured in APP_DB

### ISSUE THREAD

**Issue by volodymyrsamotiy** [Azure/sonic-swss#1029]
**Description**
During running VNET test found issue that not all required neighbors are configured correctly and as a result test fails. _(Please note, issue is general and not related to VNET functionallity)_
Issue is observed when try to check 128 VNETs, when run playbook with the ```num_vnet=128```, for example:
```
$ ansible-playbook test_sonic.yml -i inventory -e testbed_name=<testbed_name> -e testbed_type=t0 -e testcase_name=vnet_vxlan -e "num_vnet=128 num_routes=1024 num_endpoints=512"
```
After test failed go to DUT and check the following:
```
root@sonic:/home/admin# cat /tmp/vnet.nbr.json | grep Vlan | wc -l
192
root@sonic:/home/admin# redis-cli -n 4 keys "NEIGH*Vlan*" | wc -l
192
root@sonic:/home/admin# redis-cli -n 0 keys "NEIGH*Vlan*" | wc -l
37
```
As shown above test generates config ```vnet.nbr.json``` with the 192 neighbors to be configured and we do observe 192 entries in ```CONFIG_DB``` but to ```APPLICATION_DB``` only 37 neighbors was configured.
As a result some test cases are failing since many neighbors are missed and there is no way for traffic to pass.

_(BTW, with default values test passes and also passes if less VNETs are specified, e.g. ```-e "num_vnet=16 num_routes=1024 num_endpoints=512"```, since less neighbors are configure in such cases and all applied correctly)_

**Steps to reproduce the issue:**
1. Run VNET test with the large number of VNETs (it will generate config file with 192 neighbors):
```
$ ansible-playbook test_sonic.yml -i inventory -e testbed_name=<testbed_name> -e testbed_type=t0 -e testcase_name=vnet_vxlan -e "num_vnet=128 num_routes=1024 num_endpoints=512"
```
2. After test failed go to DUT and observe that all neighbors are present in ```CONFIG_DB``` but many are missed in ```APLICATION_DB```:
```
root@sonic:/home/admin# cat /tmp/vnet.nbr.json | grep Vlan | wc -l
192
root@sonic:/home/admin# redis-cli -n 4 keys "NEIGH*Vlan*" | wc -l
192
root@sonic:/home/admin# redis-cli -n 0 keys "NEIGH*Vlan*" | wc -l
37
```

**Describe the results you received:**
Many neighbor entries are not configured to ```APLICATION_DB```.

**Describe the results you expected:**
All neighbor entries should be configured to ```APLICATION_DB```.

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Comment by volodymyrsamotiy** [comment]
Found root cause, problem is in [arp_responder.py](https://github.com/Azure/sonic-mgmt/blob/master/ansible/roles/test/files/helpers/arp_responder.py), it is not designed to work with the multiple VLAN interfaces on the same physical port.

There are two issues:
- One is that ```arp_responder``` stores neighbors in a dictionary where  key is just interface name and VLAN is not taken into account. As a result, when there are two or more neighbors on the same port but different VLANs, only one is stored, all other are overwritten since key is the same and neighbors don't work. 
- Second problem is that ```ar_responder``` uses RAW socket for receiving ARP packets, but RAW socket doesn't provide VLAN tag. Kernel strips a tag and stores it in different place which is not available via RAW socket.

So, need to improve ```arp_responder``` in order to store all the neighbors correctly in case there are multiple VLAN interfaces on one port. Also need a way to receive tagged ARP packets in order to know from what VLAN interface packet arrived so then neighbor lookup can be performed in internal dictionary.

**Comment by prsunny** [comment]
Fix ready as part of - https://github.com/Azure/sonic-mgmt/pull/1201
