### ISSUE TITLE
mlnx device: pfc watchdog warm-reboot fails on test case 2 https://github.com/Azure/sonic-mgmt/pull/834

### ISSUE THREAD

**Issue by wendani** [Azure/sonic-swss#1102]
PFC storm started and detected before warm-reboot
On-going storm on warm-reboot emission, and lasts past the warm-reboot finish
PFC storm stopped and restored after warm-reboot

**Comment by wendani** [comment]
@andriymoroz-mlnx @stepanblyschak

**Comment by stepanblyschak** [comment]
@liat-grozovik @wendani @qiluo-msft you can close this issue. Seems I do not have permissions to close issues in the repository
