### ISSUE TITLE
[teammgrd] teamd cannot start when port channel was down before warm reboot

### ISSUE THREAD

**Issue by stepanblyschak** [Azure/sonic-swss#1165]
Steps to reproduce:
1. shutdown lag on peer
2. sudo warm-reboot on dut
3. observe continuous log about teamd fails to start because it cannot assign requested mac address

The issue seems to be introduced https://github.com/Azure/sonic-swss/pull/1003.

The mac that teammgrd reads form saved PDU appears to be 00:00:00:00:00:00.

**Comment by pavel-shirshov** [comment]
@shine4chen can you please check this issue?
Is it possible for you to reproduce it?

**Comment by shine4chen** [comment]
@pavel-shirshov Thank @stepanblyschak.  We have reproduce it. It seems that when you shutdown lag on peer  peer still tries to negotiate with dut , then saved pdu packet content is not suitable for restoring mac-address. We will add some pdu validation code to work it out.

**Comment by pavel-shirshov** [comment]
@stepanblyschak Can you please check the issue is fixed by the PR above?

**Comment by stepanblyschak** [comment]
@pavel-shirshov Checked. @shine4chen Thanks, it works correct now!
