### ISSUE TITLE
[VNET] Fail to remove VNET interface

### ISSUE THREAD

**Issue by volodymyrsamotiy** [Azure/sonic-swss#1174]
**Description**
VNET interface cannot be removed due to reference count is equal to ```1```.
It happens because there is no event from ```config manager``` for removing subnet route from the interface. As a result, subnet route is not remove hence interface is still in use and cannot be removed.
```
ERR swss#orchagent: :- meta_generic_validation_remove: object 0x60000000006bd reference count is 1, can't remove
ERR swss#orchagent: :- removeRouterIntfs: Failed to remove router interface for port Vlan3001, rv:-5
INFO swss#supervisord: orchagent terminate called after throwing an instance of 'std::runtime_error'
INFO swss#supervisord: orchagent   what():  Failed to remove router interface.
INFO swss#supervisord INFO exited: orchagent (terminated by SIGABRT (core dumped); not expected)
INFO swss#supervisord WARN received SIGTERM indicating exit request
```

**Steps to reproduce**
- Create VNET and VNET interface
- Remove interface
- Observe error "Failed to remove router interface"

**Expected behavior**
There is ```create subnet route``` event for VNET interface from ```config manager``` to ```vnetorch``` so it is correctly added to HW, but there is now ```remove subnet route``` in order to remove it from HW. Expected is that ```config manager``` sends remove event for VNET subnet route as well so it will be removed from HW.

**Comment by prsunny** [comment]
Fixes as part of - https://github.com/Azure/sonic-swss/pull/1225
