### ISSUE TITLE
NatOrch: No DNAT_POOL object to trigger DNAT_MISS trap

### ISSUE THREAD

**Issue by kperumalbfn** [Azure/sonic-swss#1234]
Sonic NAT Orchagent doesn't create DNAT_POOL for the DNAT Table lookup. Without DNAT Table lookup, DNAT_MISS traps are not generated.

NAT pipeline:
https://github.com/opencomputeproject/SAI/blob/master/doc/behavioral%20model/pipeline_nat_v1.pdf

Requirement:
- Sonic NAT orchagent to create DNAT_POOL objects
- Sonic NAT orchagent to pass NAT_TYPE as key in nat_entry_t while creating NAT entries. This is to avoid duplicate entries for DNAT_POOL and DEST_NAT objects. Only Master SAI has this change.

**Comment by rlhui** [comment]
@AkhileshSamineni - would you please address this?  Thanks.

**Comment by AkhileshSamineni** [comment]
@rlhui - Started working on needed changes, will raise the PR soon.

**Comment by rlhui** [comment]
thanks @AkhileshSamineni  - wondering if we have an ETA for this?

**Comment by AkhileshSamineni** [comment]
@rlhui - We are planning to raise PR with appropriate changes by May month end.

**Comment by AkhileshSamineni** [comment]
Related PRs for master branch :
https://github.com/Azure/sonic-swss/pull/1358
https://github.com/Azure/sonic-utilities/pull/1001
https://github.com/Azure/sonic-swss-common/pull/367
https://github.com/Azure/sonic-sairedis/pull/644
