### ISSUE TITLE
NAT mgr clears the iptables NAT rules added by other Apps during bootup

### ISSUE THREAD

**Issue by venkatmahalingam** [Azure/sonic-swss#1292]
Observation:
   The iptables SNAT rules added from hostcfgd during system bootup, cleaned up by some module.

Root cause:
   NAT mgr clears the iptables NAT rules added by hostcfgd during bootup.

Potential solution:
   Clear the NAT rules added only by natmgr not all rules in kernel.

NAT feature pull request:
https://github.com/Azure/sonic-swss/pull/1059

@AkhileshSamineni As discussed, please use this issue for tracking.

**Comment by AkhileshSamineni** [comment]
Raised a PR https://github.com/Azure/sonic-swss/pull/1386 to address this issue.

**Comment by arlakshm** [comment]
#1386 is merged. Closing this issue
