### ISSUE TITLE
[FDB] Doesn't flush fdb entries on port link down

### ISSUE THREAD

**Issue by MikeHcChen** [Azure/sonic-swss#1294]
Original issue was posted by [dev-aviz](https://github.com/dev-aviz) on Azure/sonic-buildimage: https://github.com/Azure/sonic-buildimage/issues/4184#issue-569290297
However, this issue should be related with Azure/sonic-swss repository, therefore I copy the issue 
in this repository.

Description
(DUT)Device Under Test does not flush mac entries on port link down.

Expected:
Switch should remove all MAC entries learned on inactive/down ports

Issue observed

Broadcom
Mellnox
Steps to reproduce the issue:

Configure Ethernet10 as trunk port and allow Vlan 10
Send L2 traffic with SMAC = 00:AA:AA:AA:AA:00 -> 00:AA:AA:AA:AA:09
Switch learns MAC address on Ethernet10 and Vlan10 correctly
Shutdown Ethernet10
Switch does not flush MAC entries learned on Ethernet10
Describe the results you received:
Device Under Test does not flush mac entries on port link down.

Describe the results you expected:
Switch should remove all MAC entries learned on inactive/down ports

[Version]
SONiC Software Version: SONiC.master.0-dirty-20191207.003133
Distribution: Debian 9.11
Kernel: 4.9.0-9-2-amd64
Build commit: f345935
Build date: Sat Dec 7 11:52:18 UTC 2019
Built by: dev-aviz@aviznetworks.com

Platform: x86_64-accton_as5712_54x-r0
HwSKU: Accton-AS5712-54X
ASIC: broadcom
Serial Number: 571254X1630035
Uptime: 20:09:57 up 2:53, 1 user, load average: 1.88, 2.05, 2.06

How to validate the results:

[Console]
root@spine1:~# show vlan config
Name VID Member Mode

Vlan10 10 Ethernet0 tagged
Vlan10 10 Ethernet10 tagged
root@spine1:~#

root@spine1:~# show interface status Ethernet10
Interface Lanes Speed MTU Alias Vlan Oper Admin Type Asym PFC

Ethernet10 27 10G 9100 tenGigE10 trunk down down SFP/SFP+/SFP28 N/A
root@spine1:~# show mac
No. Vlan MacAddress Port Type

1      10  00:AA:AA:AA:AA:06  Ethernet10  Dynamic
2      10  00:AA:AA:AA:AA:02  Ethernet10  Dynamic
3      10  00:AA:AA:AA:AA:03  Ethernet10  Dynamic
4      10  00:AA:AA:AA:AA:05  Ethernet10  Dynamic
5      10  00:AA:AA:AA:AA:08  Ethernet10  Dynamic
6      10  00:AA:AA:AA:AA:04  Ethernet10  Dynamic
7      10  00:AA:AA:AA:AA:01  Ethernet10  Dynamic
8      10  00:AA:AA:AA:AA:00  Ethernet10  Dynamic
9      10  00:AA:AA:AA:AA:09  Ethernet10  Dynamic
10 10 00:AA:AA:AA:AA:07 Ethernet10 Dynamic
Total number of entries 10

**Comment by MikeHcChen** [comment]
I found on other platforms (ex: 'x86_64-delta_ag9032v1-r0' with SONiC Software Version: 201911 branch commit 2218ed4cc50aebba681b42f300869c84c90be613 on May 1, 2020) also have this issue.

Test log: 
[FDB_issue.txt](https://github.com/Azure/sonic-swss/files/4627233/FDB_issue.txt)

**Comment by prsunny** [comment]
@MikeHcChen , this issue should be fixed by https://github.com/Azure/sonic-swss/pull/1242. Can you please check and close?

**Comment by MikeHcChen** [comment]
> @MikeHcChen , this issue should be fixed by #1242. Can you please check and close?

OK. Thanks.
