### ISSUE TITLE
port is not brought up after init

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-swss#130]
The port is not brought up after init. In the sai api record, it sets the port admin state to false in the end.

[sairedis.2016-11-10.03_35_51.976755.txt](https://github.com/Azure/sonic-swss/files/582494/sairedis.2016-11-10.03_35_51.976755.txt)

**Comment by kcudnik** [comment]
All ports here are set to false

**Comment by lguohan** [comment]
yes, i suspect there is bug in sonic-swss that did not setup them to true. @stcheng

**Comment by stcheng** [comment]
https://github.com/Azure/sonic-buildimage/pull/381 with this pull request the issue is not seen for now.
