### ISSUE TITLE
CONFIG_DB is not in sync with APP_DB when adding NAT_BINDINGS entries

### ISSUE THREAD

**Issue by jciesiex** [Azure/sonic-swss#1309]
Steps to reproduce:

sudo config nat feature enable

echo '{"NAT_POOL": {"test_pool": {"nat_ip": "10.0.0.34","nat_port": "8000-9000"}},

"ACL_TABLE": {"test_acl": {"stage": "INGRESS","type": "L3","policy_desc": "test_policy","ports": ["Ethernet68"]}},

"NAT_BINDINGS": {"test_binding": {"access_list": "test_acl","nat_pool": "test_pool"}}}' > dynamic.json

sonic-cfggen -j dynamic.json --write-to-db

redis-dump -d 4 --pretty -k BINDING
redis-dump -d 0 --pretty -k BINDING
Observed behavior:

CONFIG_DB
{
"NAT_BINDINGS|test_binding": {
"type": "hash",
"value": {
"access_list": "test_acl",
"nat_pool": "test_pool"
}
}
}

APP_DB
no entries found

Expected behavior:
CONFIG_DB and APP_DB should be in sync

**Comment by AkhileshSamineni** [comment]
@jciesiex  NAT Bindings will be at CONFIG_DB only.
Based on NAT_BINDINGS table, NAT manager will add iptables NAT rules which are used for dynamic NAT translations and NAT_BINDINGS table is not pushed to APPL_DB. This is expected behavior only.

**Comment by arlakshm** [comment]
Expected behaviour
