### ISSUE TITLE
[NAT] swss error when adding Loopback interface to NAT zone

### ISSUE THREAD

**Issue by SavchukRomanLv** [Azure/sonic-swss#1311]
Steps to reproduce:
1. Enable NAT feature:
`sudo config nat feature enable`
2. Add Loopback interface to NAT zone 1
`sudo config nat add interface Loopback0 -nat_zone 1`

**Actual result:** error in syslog appears, Loopback NAT zone changed to 1
**Expected result:**  Loopback NAT zone changed to 1, no error in syslog

**Log file:**
--write-to-db removes=None argv=None warn=True chdir=None stdin_add_newline=True stdin=None
Apr 21 11:44:33.805637 cab18-3-dut INFO swss#supervisord: intfmgrd RTNETLINK answers: File exists
Apr 21 11:44:33.805637 cab18-3-dut ERR swss#intfmgrd: :- exec: /sbin/ip link add Loopback0 mtu 65536 type dummy && /sbin/ip link set Loopback0 up: Success
Apr 21 11:44:33.805637 cab18-3-dut ERR swss#intfmgrd: :- addLoopbackIntf: Command '/sbin/ip link add Loopback0 mtu 65536 type dummy && /sbin/ip link set Loopback0 up' failed with rc 512

**Environment:** 
SONiC Software Version: SONiC.201911.24-dirty-20200420.130540
Distribution: Debian 9.12
Kernel: 4.9.0-11-2-amd64

Platform: x86_64-arista_7170_64c
HwSKU: Arista-7170-64C

**Comment by AkhileshSamineni** [comment]
@SavchukRomanLv  Raised PR https://github.com/Azure/sonic-swss/pull/1411 to fix this issue.

**Comment by SavchukRomanLv** [comment]
@AkhileshSamineni still reproducible with SONiC 201911 #155. Looks for me that Avoid adding loopback interface (ip link add) when setting nat zone on loopback interface #1411 was not merged into 201911 branch

**Comment by arlakshm** [comment]
Issue is fixed.
