### ISSUE TITLE
swss/test_port.py failed

### ISSUE THREAD

**Issue by BrynXu** [Azure/sonic-swss#1324]
**Steps to reproduce the issue:**
1. docker run --privileged -id --name sw debian bash
2. sudo ./create_vnet.sh sw
3. docker run --privileged -v /var/run/redis-vs/sw:/var/run/redis --network container:sw -d --name vs docker-sonic-vs
4. sudo pytest -s -v test_port.py --dvsname=vs 

**Describe the results you received:**
conftest.py:240: in __init__                     
    self.check_ctn_status_and_db_connect()       
conftest.py:259: in check_ctn_status_and_db_connect                                               
    self.init_asicdb_validator()                 
conftest.py:409: in init_asicdb_validator        
    self.asicdb = AsicDbValidator(self)          
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <conftest.AsicDbValidator object at 0x7f309ff1e050>, dvs = <conftest.DockerVirtualSwitch object at 0x7f309e22f350>                                                                           

    def __init__(self, dvs):                     
        self.adb = swsscommon.DBConnector(1, dvs.redis_sock, 0)                                   
                                                 
        # get default dot1q vlan id              
        atbl = swsscommon.Table(self.adb, "ASIC_STATE:SAI_OBJECT_TYPE_VLAN")                      
                                                 
        keys = atbl.getKeys()                    
        assert len(keys) == 1                    
        self.default_vlan_id = keys[0]           
                                                 
        # build port oid to front port name mapping                                               
        self.portoidmap = {}                     
        self.portnamemap = {}                     
        self.hostifoidmap = {}                   
        self.hostifnamemap = {}                  
        atbl = swsscommon.Table(self.adb, "ASIC_STATE:SAI_OBJECT_TYPE_HOSTIF")                    
        keys = atbl.getKeys()                    
                                                 
>       assert len(keys) == 32                   
E       assert 2 == 32                           
E         -2                                    
E         +32                                    

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**
If I changed step2 as `sudo ./create_vnet.sh -n 32 sw`
then the test can pass, it seems swss/tests/README.md need be updated to indicate this.
    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by rlhui** [comment]
@BrynXu  - will you please include version info that this was found?  Is this an issue with 20191130 release too?

**Comment by daall** [comment]
@rlhui this is an oversight in the README, not an image issue. @BrynXu thank you for reporting this, I will update the README today. :)
