### ISSUE TITLE
tlm_teamd and orhagent error while adding new LAG to sonic 

### ISSUE THREAD

**Issue by SavchukRomanLv** [Azure/sonic-swss#1346]
**Description:** 
While run test config error appears in syslog: 
```
ERR teamd#tlm_teamd: :- add_lag: Can't connect to teamd LAG='PortChannelTest', error='Invalid argument'
ERR swss#orchagent: :- update: Failed to get port PortChannelTest bind port ID
```
**Steps to reproduce:** 
**1-st option:** In SONiC CLI execute: `config portchannel add PortChannelTest`
**2-nd option: run config test:** 
`py.test --testbed=cab18-5-bfn-t0 --inventory= --testbed_file= --host-pattern= 0 --module-path=/var/user/jenkins/bfn-sonic-mgmt/ansible/library pc/test_po_update.py -v -rA`

**Expected result:** new LAG was added without any errors in syslog / test passed
**Actual result:** test fails, error appears 

**Environment:** 
SONiC Software Version: SONiC.HEAD.709-dirty-20200707.221645
Distribution: Debian 10.4
Kernel: 4.19.0-6-2-amd64
Build commit: 31baf381

**Comment by pavel-shirshov** [comment]
I've added a fix, which will fix this error message
`ERR teamd#tlm_teamd: :- add_lag: Can't connect to teamd LAG='PortChannelTest', error='Invalid argument'`

The fix will not fix the following error message: `ERR swss#orchagent: :- update: Failed to get port PortChannelTest bind port ID`
