### ISSUE TITLE
Failed to set default drop route to a new next hop

### ISSUE THREAD

**Issue by stcheng** [Azure/sonic-swss#139]
To have deterministic behavior, when the orchagent start, it creates IPv4 and IPv6 default route and set it to DROP. 

Later we learn the default routes and the orchagent reset these routes to some new next hop IDs and set the packet action to FORWARD. 

However, Mellanox SAI has an issue to set the route from DROP to FORWARD with next hop ID with using set_attribute API.

**Comment by xinliu-seattle** [comment]
MLNX related. Liat please help to assign to the right dev. thanks.

**Comment by oleksandrivantsiv** [comment]
The root cause of the issue is both orchagent implementation and Mellanox SAI:

- Mellanox SAI:
It is not possible to set next hop for routes with actions drop. And not possible to set action forward for routes without next hops:
```
Dec  5 10:42:04 arc-switch1028 docker[9153]: Dec 05 10:42:04 NOTICE  SAI_UTILS: mlnx_sai_utils.c[465]- set_dispatch_attrib_handler: Set Route next hop ID, key:route 0.0.0.0 0.0.0.0, val:Nex
t hop,2,000000
Dec  5 10:42:04 arc-switch1028 docker[9153]: Dec 05 10:42:04 NOTICE  SAI_UTILS: mlnx_sai_utils.c[465]- set_dispatch_attrib_handler: Set Route packet action, key:route 0.0.0.0 0.0.0.0, val:1
Dec  5 10:42:04 arc-switch1028 docker[9153]: Dec 05 10:42:04 ERROR   SX_API_ROUTER: sx_api_router.c[1368]- sx_api_router_uc_route_set: Next hop uc route must have a valid next_hop_cnt or a
valid ecmp_id
Dec  5 10:42:04 arc-switch1028 docker[9153]: Dec 05 10:42:04 ERROR   SAI_ROUTE: mlnx_sai_route.c[577]- mlnx_modify_route: Failed to set route - Parameter Error.
Dec  5 10:42:04 arc-switch1028 docker[9153]: Dec 05 10:42:04 ERROR   SAI_UTILS: mlnx_sai_utils.c[586]- sai_set_attribute: Failed set attrib dispatch
Dec  5 10:42:04 arc-switch1028 syncd: :- processEvent: failed to execute api: set, key: SAI_OBJECT_TYPE_ROUTE_ENTRY:{"dest":"0.0.0.0/0","vr":"oid:0x3000000000022"}, status: SAI_STATUS_INVAL
ID_PARAMETER
Dec  5 10:42:04 arc-switch1028 syncd: :- processEvent:  field: SAI_ROUTE_ATTR_PACKET_ACTION, value: SAI_PACKET_ACTION_FORWARD
Dec  5 10:42:04 arc-switch1028 syncd: :- exit_and_notify: sending switch_shutdown_request notification to OA
```

- Orchagent:
Missing functionality that changes route packet action from drop to forward for default route.

**Comment by stcheng** [comment]
@oleksandrivantsiv the functionality of switching the packet action from drop to forward is in pull request #138. Once the SAI supports this, we will need to re-open #138 and merge it.

**Comment by liatgrozovik** [comment]
We would like to verify the solution works, so can you share the code of orchagent so we will verify and approve working from our side?

**Comment by stcheng** [comment]
In order to verify the solution works, it is okay to just cherry-pick the #138 change on top of the current master to build a new orchagent daemon.

**Comment by stcheng** [comment]
https://github.com/opencomputeproject/SAI/pull/324 
I have updated SAI v0.9.4 with comments to describe the scenario we meet here.

**Comment by stcheng** [comment]
#145 resolves this.
