### ISSUE TITLE
[dvs/NAT] test_VerifyConntrackTimeoutForNatEntry behavior is inconsistent

### ISSUE THREAD

**Issue by daall** [Azure/sonic-swss#1409]
test_VerifyConntrackTimeoutForNatEntry in the NAT tests checks for this:
```
if int(conntrack_list[proto_index + 7]) < 432000 and int(conntrack_list[proto_index + 7]) > 431900:
    <test fails>
```

However when running the tests, `int(conntrack_list[proto_index + 7])` consistently returns 431995.

The feature owner needs to confirm whether this value is expected or not, and fix either the feature or the test behavior.

See #1408.

**Comment by AkhileshSamineni** [comment]
@daall  @rlhui  int(conntrack_list[proto_index + 7]) returns 431995 is valid only, I will fix the test behavior.
