### ISSUE TITLE
Repeated error messages for 'still referenced neighbor' by orchagent

### ISSUE THREAD

**Issue by hrachya-mellanox** [Azure/sonic-swss#142]
Orchagent is repeatedly, with approximately 1 second interval, printing following message in /var/log/syslog

Example:
Dec  1 22:16:29 str-msn2700-04 ERR orchagent: :- removeNeighbor: Neighbor is still referenced ip:10.0.0.31
Dec  1 22:16:30 str-msn2700-04 ERR orchagent: :- removeNeighbor: Neighbor is still referenced ip:10.0.0.31
Dec  1 22:16:30 str-msn2700-04 ERR orchagent: :- removeNeighbor: Neighbor is still referenced ip:10.0.0.31
Dec  1 22:16:31 str-msn2700-04 ERR orchagent: :- removeNeighbor: Neighbor is still referenced ip:10.0.0.31

The error needs to be investigated.
Another issue is that the syslog is constantly growing in size by the repeated messages.

**Comment by lguohan** [comment]
@stcheng , please comment.

**Comment by stcheng** [comment]
This is already addressed in #137
