### ISSUE TITLE
segfault teammgrd and orchagent errors while adding new LAG to sonic

### ISSUE THREAD

**Issue by OlaOliynyk** [Azure/sonic-swss#1428]
**Description**:
While run test config errors appear in log:
`tlm_teamd: segfault at 0 ip 0000562605442b58 sp 00007fff6688edb0 error 4 in tlm_teamd`
`ERR teamd#teammgrd: :- addLagMember: Failed to add Ethernet112 to port channel PortChanne`
`ERR swss#orchagent: :- removeLag: Failed to remove ref count 1 LAG PortChannel'`

**Steps to reproduce**:
 **Run config test**:
`py.test         --testbed=t0         --inventory=         --testbed_file=         --host-pattern=t0         --module-path=/var/user/jenkins/sonic-mgmt/ansible/library         pc/test_po_update.py         -v -rA`

**Expected result**: new LAG added/removed without any errors in syslog / test passed
**Actual result**: test fails, error appears

**Environment**:
SONiC Software Version: SONiC.HEAD.761-dirty-20200903.072206
Distribution: Debian 10.5
Kernel: 4.19.0-9-2-amd64
Build commit: dd908c2e

**Comment by OlaOliynyk** [comment]
Duplicate https://github.com/Azure/sonic-buildimage/issues/5306

**Comment by pavel-shirshov** [comment]
Hi @OlaOliynyk 
The #5306 is about tlm_teamd. Your report is about teammgrd. Can you please double check?
