### ISSUE TITLE
Mirror feature issues

### ISSUE THREAD

**Issue by stcheng** [Azure/sonic-swss#154]
1. When creating the mirror session I notice that the VLAN ID is 1. Where is this number coming from? Why the port VLAN ID is 1 and used here? Do we need to have a default VLAN ID here?
2. TOS is zero even when DSCP is set.

**Comment by stcheng** [comment]
https://github.com/Azure/sonic-swss/pull/163 resolves the second issue.

**Comment by oleksandrivantsiv** [comment]
@stcheng both issues were resolved. Can you please verify and close?

**Comment by lguohan** [comment]
@stcheng, is this resolved?

**Comment by stcheng** [comment]
yes. it is resolved. thanks.
