### ISSUE TITLE
Should we explicitly indicate the specific branch version?

### ISSUE THREAD

**Issue by Pterosaur** [Azure/sonic-swss#1589]
https://github.com/Azure/sonic-swss/blob/693a02ceb669d6ecfb616183068225051aafe3e3/azure-pipelines.yml#L36-L42

Here is the Spec of AzurePipeline: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/download-pipeline-artifact?view=azure-devops

![image](https://user-images.githubusercontent.com/18609639/104122193-76db4b80-537e-11eb-82c7-7ffd3c4aedf5.png)

According to my understanding, if you don't explicitly indicate the artifact you want to download, it will fetch the latest build artifact that may be a PR artifact.
So , I think the following attributes that should be added to indicate a stable artifact in the master branch.
```yml
    runVersion: LatestFromBranch
    runBranch: refs/heads/master
```

**Comment by lguohan** [comment]
okay. looks reasonable.
