### ISSUE TITLE
Separate LAG/LAG_MEMBER and VLAN/VLAN_MEMBER tables

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-swss#160]
We should seperate LAG_TABLE veruse LAG_MEMBER_TABLE, they are different and have different schema.

acsadmin@str-s6000-acs-11:~$ redis-cli keys LAG_TABLE:PortChannel*
 1) "LAG_TABLE:PortChannel8:Ethernet8"
 2) "LAG_TABLE:PortChannel0:Ethernet4"
 3) "LAG_TABLE:PortChannel32"
 4) "LAG_TABLE:PortChannel32:Ethernet32"
 5) "LAG_TABLE:PortChannel24:Ethernet28"
 6) "LAG_TABLE:PortChannel16"
 7) "LAG_TABLE:PortChannel24:Ethernet24"
 8) "LAG_TABLE:PortChannel40:Ethernet44"
 9) "LAG_TABLE:PortChannel48:Ethernet48"
10) "LAG_TABLE:PortChannel56"
11) "LAG_TABLE:PortChannel0:Ethernet0"
12) "LAG_TABLE:PortChannel48"
13) "LAG_TABLE:PortChannel56:Ethernet56"
14) "LAG_TABLE:PortChannel8:Ethernet12"
15) "LAG_TABLE:PortChannel16:Ethernet20"
16) "LAG_TABLE:PortChannel32:Ethernet36"
17) "LAG_TABLE:PortChannel40"
18) "LAG_TABLE:PortChannel40:Ethernet40"
19) "LAG_TABLE:PortChannel0"
20) "LAG_TABLE:PortChannel48:Ethernet52"
21) "LAG_TABLE:PortChannel8"
22) "LAG_TABLE:PortChannel16:Ethernet16"
23) "LAG_TABLE:PortChannel24"
24) "LAG_TABLE:PortChannel56:Ethernet60"

**Comment by stcheng** [comment]
Update this issue.
VLAN has the same issue and might also be separated into VLAN and VLAN_MEMBER tables.

**Comment by stcheng** [comment]
https://github.com/Azure/sonic-swss-common/pull/84

**Comment by lguohan** [comment]
@pavel-shirshov , can you split the vlan/vlan_member table?

**Comment by pavel-shirshov** [comment]
Started working on this task yesterday.

**Comment by pavel-shirshov** [comment]
https://github.com/Azure/sonic-swss/pull/229

**Comment by pavel-shirshov** [comment]
Fixed
