### ISSUE TITLE
adding allow-hotplug in the etc interface files so that we do not need ifup in the portsyncd

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-swss#165]
network/interfaces has this “allow-hotplug” stanza, should fire when netdevs are added

this way portsyncd doesn’t need to know about ifup
  
but you can still define the network config there

**Comment by stcheng** [comment]
👍

**Comment by stcheng** [comment]
tested this method works for both port based host interfaces and LAG based host interfaces.

**Comment by stcheng** [comment]
After the above two pull requests merged, there are still some work needs to be done on the teamsyncd side to ensure that during docker-swss/docker-teamd restart, teamsyncd can gracefully handle the events.

**Comment by stcheng** [comment]
Close this issue and track the teamd restart issue at https://github.com/Azure/SONiC/issues/40
