### ISSUE TITLE
CoPP manager feature logic is missing.

### ISSUE THREAD

**Issue by caizhenghui-juniper** [Azure/sonic-swss#1939]
In this block of code, the logic is default to implicit feature enabled. Which is not covering the case that feature is not in init config and config db. 
e.g. if include_sflow is not true, init config will not have the entry, and if there is no explicit feature disable entry in Config DB for SFLOW, the logic here will not put trap group for sFlow in disabled trapgroupid. This will result in copporch trying to create GENETLINK hostif. This will cause issue if ASIC doesn't support SFLOW and likely doesn't support GENETLINK hostif 
Please check. 
https://github.com/Azure/sonic-swss/blob/da49332b80853d5dd1e88f92f266e4970d8112a8/cfgmgr/coppmgr.cpp#L253-L265

**Comment by prsunny** [comment]
This is planned to fix as part of - https://github.com/Azure/sonic-buildimage/issues/8686

**Comment by caizhenghui-juniper** [comment]
@prsunny Thanks for the quick reply, I'm closing the issue.
