### ISSUE TITLE
Not all expected environment variables are export before orchagent start 

### ISSUE THREAD

**Issue by oleksandrivantsiv** [Azure/sonic-swss#265]
The following lines of code expects environment variable which are not exported:
https://github.com/Azure/sonic-swss/blob/f9d9f181660617d7cf0685af0d6eb6a9ce190972/orchagent/qosorch.cpp#L579
https://github.com/Azure/sonic-swss/blob/d1fdf399e1e0e2e0d71fad1bce2ea7babee2eb48/orchagent/aclorch.cpp#L873

**Comment by stcheng** [comment]
Hi Sasha, could you help fix this issue?

**Comment by lguohan** [comment]
on which branch? master or 1.0.1?

**Comment by stcheng** [comment]
according to this fix: https://github.com/Azure/sonic-buildimage/pull/835, it should be both on master and v1.0.1
