### ISSUE TITLE
Does program need to call API to stop/deinit the ASIC in the case?

### ISSUE THREAD

**Issue by kaiyu22** [Azure/sonic-swss#266]
If in case, the program runs to here "on_switch_shutdown_request()".
(notifications.cpp, line 70)

Does program need to call API (e.g. shutdown_switch) to notify chip vendor stop/deinit the ASIC?

**Comment by stcheng** [comment]
Right now we don't call this API specifically. Because at this moment, the syncd is already crashed and this indicates that no more APIs could be executed.
During the next time's switch initialization, the switch will be initialized again to the default state.

**Comment by kaiyu22** [comment]
I got it. Thanks for your reply.
