### ISSUE TITLE
FpmLink's readMe() is not called, Why?

### ISSUE THREAD

**Issue by MaoJianwei** [Azure/sonic-swss#309]
If not called, how can fpmlink receive new route message?

And I don't find readMe() is registered anywhere.

https://github.com/Azure/sonic-swss/blob/7f5eca5e858f6a82966eed4564ded4c3646424bf/fpmsyncd/fpmsyncd.cpp#L37

**Comment by stcheng** [comment]
You could check the `sonic-swss-common` library
