### ISSUE TITLE
Who will invoke RouteSync::onMsg(...)? and Where can I find "netmsg.h"?

### ISSUE THREAD

**Issue by MaoJianwei** [Azure/sonic-swss#310]
https://github.com/Azure/sonic-swss/blob/7f5eca5e858f6a82966eed4564ded4c3646424bf/fpmsyncd/routesync.cpp#L24

**Comment by stcheng** [comment]
Hello Jianwei,

Please check the `swss-common` library to see how the `onMsg` function gets invoked.
Also, the `netmsg.h` file is in that folder.
