### ISSUE TITLE
orchagent hangs at switchorch due to erase operation on map

### ISSUE THREAD

**Issue by JipanYanga** [Azure/sonic-swss#347]
(gdb) bt
#0  0x00007febafeae697 in std::_Rb_tree_increment(std::_Rb_tree_node_base*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000000000485218 in operator++ (this=<synthetic pointer>) at /usr/include/c++/4.9/bits/stl_tree.h:203
#2  erase (__position=..., this=0x2340f50) at /usr/include/c++/4.9/bits/stl_tree.h:867
#3  erase (__position=..., this=0x2340f50) at /usr/include/c++/4.9/bits/stl_map.h:732
#4  SwitchOrch::doTask (this=<optimized out>, consumer=...) at switchorch.cpp:95
#5  0x0000000000418860 in Orch::execute (this=this@entry=0x2340db0, tableName="SWITCH_TABLE") at orch.cpp:141
#6  0x0000000000410991 in OrchDaemon::start (this=this@entry=0x2340660) at orchdaemon.cpp:156
#7  0x0000000000408cb5 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:300

(gdb) p consumer.m_toSync
$8 = std::map with 0 elements
(gdb) c 
Continuing.
^C
Program received signal SIGINT, Interrupt.
0x00007febafeae697 in std::_Rb_tree_increment(std::_Rb_tree_node_base*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
(gdb) bt
#0  0x00007febafeae697 in std::_Rb_tree_increment(std::_Rb_tree_node_base*) () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x0000000000485218 in operator++ (this=<synthetic pointer>) at /usr/include/c++/4.9/bits/stl_tree.h:203
#2  erase (__position=..., this=0x2340f50) at /usr/include/c++/4.9/bits/stl_tree.h:867
#3  erase (__position=..., this=0x2340f50) at /usr/include/c++/4.9/bits/stl_map.h:732
#4  SwitchOrch::doTask (this=<optimized out>, consumer=...) at switchorch.cpp:95
#5  0x0000000000418860 in Orch::execute (this=this@entry=0x2340db0, tableName="SWITCH_TABLE") at orch.cpp:141
#6  0x0000000000410991 in OrchDaemon::start (this=this@entry=0x2340660) at orchdaemon.cpp:156
#7  0x0000000000408cb5 in main (argc=<optimized out>, argv=<optimized out>) at main.cpp:300
(gdb)

**Comment by stcheng** [comment]
thanks for reporting this bug

**Comment by JipanYanga** [comment]
Already fixed with https://github.com/Azure/sonic-swss/pull/348,  closing it.
