### ISSUE TITLE
Orchagent crashing at boot up time

### ISSUE THREAD

**Issue by yxieca** [Azure/sonic-swss#421]
It appears to be a race condition at boot up time. This new DUT has lots of more ports compare to any other device we tested before.

Dec 20 09:51:17.789591 str-7260cx3-acs-2 INFO supervisord: lldpd 2017-12-20T09:51:17 [WARN/interfaces] error while receiving frame on Ethernet260: Network is down
Dec 20 09:51:18.260132 str-7260cx3-acs-2 NOTICE orchagent: :- addLagMember: Add member Ethernet60 to LAG PortChannel02 lid:200000000144c pid:100000000002d
Dec 20 09:51:18.260663 str-7260cx3-acs-2 NOTICE orchagent: :- addLagMember: Add member Ethernet56 to LAG PortChannel02 lid:200000000144c pid:100000000002c
Dec 20 09:51:18.261266 str-7260cx3-acs-2 INFO kernel: [   48.273659] IPv6: ADDRCONF(NETDEV_CHANGE): PortChannel02: link becomes ready
Dec 20 09:51:18.372625 str-7260cx3-acs-2 NOTICE orchagent: :- addLagMember: Add member Ethernet64 to LAG PortChannel03 lid:200000000144d pid:100000000003f
Dec 20 09:51:18.373325 str-7260cx3-acs-2 INFO kernel: [   48.389155] IPv6: ADDRCONF(NETDEV_CHANGE): PortChannel03: link becomes ready
Dec 20 09:51:18.374288 str-7260cx3-acs-2 NOTICE orchagent: :- addLagMember: Add member Ethernet68 to LAG PortChannel03 lid:200000000144d pid:1000000000040
Dec 20 09:51:18.531138 str-7260cx3-acs-2 ERR orchagent: :- meta_generic_validation_objlist: SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID:SAI_ATTR_VALUE_TYPE_OBJECT_ID object on list [0] oid 0x3a00000000154c object type 58 does not exists in local DB
Dec 20 09:51:18.531138 str-7260cx3-acs-2 ERR orchagent: :- meta_sai_on_fdb_event_single: failed to insert SAI_OBJECT_TYPE_FDB_ENTRY:{"bvid":"oid:0x26000000000088","mac":"52:54:00:01:0D:6F","switch_id":"oid:0x21000000000000"} received in notification: SAI_STATUS_INVALID_PARAMETER
Dec 20 09:51:18.531163 str-7260cx3-acs-2 ERR orchagent: :- update: Failed to get port by bridge port ID 16325548649223500
Dec 20 09:51:18.531224 str-7260cx3-acs-2 ERR orchagent: :- meta_generic_validation_objlist: SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID:SAI_ATTR_VALUE_TYPE_OBJECT_ID object on list [0] oid 0x3a00000000154d object type 58 does not exists in local DB
Dec 20 09:51:18.531253 str-7260cx3-acs-2 ERR orchagent: :- meta_sai_on_fdb_event_single: failed to insert SAI_OBJECT_TYPE_FDB_ENTRY:{"bvid":"oid:0x26000000000088","mac":"52:54:00:1C:21:EB","switch_id":"oid:0x21000000000000"} received in notification: SAI_STATUS_INVALID_PARAMETER
Dec 20 09:51:18.531265 str-7260cx3-acs-2 ERR orchagent: :- update: Failed to get port by bridge port ID 16325548649223501
Dec 20 09:51:18.531562 str-7260cx3-acs-2 ERR orchagent: :- meta_generic_validation_objlist: SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID:SAI_ATTR_VALUE_TYPE_OBJECT_ID object on list [0] oid 0x3a00000000154e object type 58 does not exists in local DB
Dec 20 09:51:18.531562 str-7260cx3-acs-2 ERR orchagent: :- meta_sai_on_fdb_event_single: failed to insert SAI_OBJECT_TYPE_FDB_ENTRY:{"bvid":"oid:0x26000000000088","mac":"52:54:00:0E:2C:2E","switch_id":"oid:0x21000000000000"} received in notification: SAI_STATUS_INVALID_PARAMETER
Dec 20 09:51:18.531576 str-7260cx3-acs-2 ERR orchagent: :- update: Failed to get port by bridge port ID 16325548649223502
Dec 20 09:51:18.531791 str-7260cx3-acs-2 ERR orchagent: :- meta_generic_validation_objlist: SAI_FDB_ENTRY_ATTR_BRIDGE_PORT_ID:SAI_ATTR_VALUE_TYPE_OBJECT_ID object on list [0] oid 0x3a00000000154f object type 58 does not exists in local DB
Dec 20 09:51:18.531791 str-7260cx3-acs-2 ERR orchagent: :- meta_sai_on_fdb_event_single: failed to insert SAI_OBJECT_TYPE_FDB_ENTRY:{"bvid":"oid:0x26000000000088","mac":"52:54:00:C3:20:2A","switch_id":"oid:0x21000000000000"} received in notification: SAI_STATUS_INVALID_PARAMETER
Dec 20 09:51:18.531826 str-7260cx3-acs-2 ERR orchagent: :- update: Failed to get port by bridge port ID 16325548649223503
Dec 20 09:51:18.534779 str-7260cx3-acs-2 ERR syncd: _brcm_sai_nbr_bcast_update:1984 Neighbor table lookup failed with error Entry not found (0xfffffff9).
Dec 20 09:51:18.534794 str-7260cx3-acs-2 ERR syncd: brcm_sai_create_lag_member:551 bcast ip update failed with error -7.
Dec 20 09:51:18.534850 str-7260cx3-acs-2 ERR syncd: :- processEvent: attr: SAI_LAG_MEMBER_ATTR_LAG_ID: oid:0x200000000144c
Dec 20 09:51:18.534858 str-7260cx3-acs-2 ERR syncd: :- processEvent: attr: SAI_LAG_MEMBER_ATTR_PORT_ID: oid:0x100000000002d
Dec 20 09:51:18.534895 str-7260cx3-acs-2 ERR syncd: :- processEvent: failed to execute api: create, key: SAI_OBJECT_TYPE_LAG_MEMBER:oid:0x1b000000001548, status: SAI_STATUS_ITEM_NOT_FOUND
Dec 20 09:51:18.534911 str-7260cx3-acs-2 ERR syncd: :- syncd_main: Runtime error: :- processEvent: failed to execute api: create, key: SAI_OBJECT_TYPE_LAG_MEMBER:oid:0x1b000000001548, status: SAI_STATUS_ITEM_NOT_FOUND
Dec 20 09:51:18.534949 str-7260cx3-acs-2 NOTICE syncd: :- exit_and_notify: sending switch_shutdown_request notification to OA
Dec 20 09:51:18.534962 str-7260cx3-acs-2 NOTICE orchagent: :- handle_switch_shutdown_request: switch shutdown request
Dec 20 09:51:18.535062 str-7260cx3-acs-2 NOTICE syncd: :- exit_and_notify: notification send successfull
Dec 20 09:51:18.535073 str-7260cx3-acs-2 WARNING syncd: :- exit_and_notify: sleep forever to keep data plane active
Dec 20 09:51:18.536512 str-7260cx3-acs-2 INFO supervisord: orchagent terminate called after throwing an instance of 'std::invalid_argument'
Dec 20 09:51:18.536536 str-7260cx3-acs-2 INFO supervisord: orchagent   what():  parse error - unexpected end of input
Dec 20 09:51:18.688785 str-7260cx3-acs-2 INFO swss.sh[1728]: 2017-12-20 09:51:18,688 INFO exited: orchagent (terminated by SIGABRT (core dumped); not expected)
Dec 20 09:51:19.049263 str-7260cx3-acs-2 INFO kernel: [   49.063601] IPv6: ADDRCONF(NETDEV_CHANGE): PortChannel01: link becomes ready
Dec 20 09:51:19.469275 str-7260cx3-acs-2 INFO kernel: [   49.480906] IPv6: ADDRCONF(NETDEV_CHANGE): PortChannel04: link becomes ready
Dec 20 09:51:19.859475 str-7260cx3-acs-2 INFO supervisord 2017-12-20 09:51:10,467 INFO success: arp_update entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Dec 20 09:51:19.859475 str-7260cx3-acs-2 INFO supervisord 2017-12-20 09:51:10,483 INFO exited: start.sh (exit status 0; expected)
Dec 20 09:51:19.859475 str-7260cx3-acs-2 INFO supervisord 2017-12-20 09:51:18,688 INFO exited: orchagent (terminated by SIGABRT (core dumped); not expected)

**Comment by stcheng** [comment]
if you have the sairedis record file it would be easier to check what API calls are executed and why it crashed in the syncd.

**Comment by prsunny** [comment]
Based on preliminary analysis, new feature code is resulting in failure. BRCM CSP raised.

**Comment by lguohan** [comment]
BRCM SAI issue. closed.
