### ISSUE TITLE
swss-schema.md does not include IPv6 ACL

### ISSUE THREAD

**Issue by alanyen1976** [Azure/sonic-swss#469]
as the title, the schema file lacks of IPv6 ACL portion. I found another document for IPv6 ACL enhancement (https://github.com/Azure/SONiC/blob/gh-pages/doc/ACL-enhancements-on-SONIC.docx). But, I think to have a single place to get all schema is a wonderful thing. So, I suggest, at least, for each sonic's 3-month release, add a check point to update the schema file before the release is welcome.

**Comment by lguohan** [comment]
@zhenggen-xu , can you take a look and add?

**Comment by stcheng** [comment]
https://github.com/Azure/sonic-swss/pull/490
