### ISSUE TITLE
Priority setting for ports_tables in orchagent

### ISSUE THREAD

**Issue by jipanyang** [Azure/sonic-swss#513]
What is reason of setting APP_VLAN_TABLE_NAME the same priority as APP_LAG_TABLE_NAME? 

Since LAG could be member of VLAN, it looks to me lag table should have higher priority than vlan table.   How about  we change it to  { APP_LAG_TABLE_NAME,         portsorch_base_pri + 4 }?  thanks.

https://github.com/Azure/sonic-swss/blob/4df9c289a6c2d41e4dee09f3055f0ac6d8e98ded/orchagent/orchdaemon.cpp#L55
```
    vector<table_name_with_pri_t> ports_tables = {
        { APP_PORT_TABLE_NAME,        portsorch_base_pri + 5 },
        { APP_VLAN_TABLE_NAME,        portsorch_base_pri + 2 },
        { APP_VLAN_MEMBER_TABLE_NAME, portsorch_base_pri     },
        { APP_LAG_TABLE_NAME,         portsorch_base_pri + 2 },
        { APP_LAG_MEMBER_TABLE_NAME,  portsorch_base_pri     }
    };
```

**Comment by pavel-shirshov** [comment]
https://github.com/Azure/sonic-swss/issues/513

**Comment by pavel-shirshov** [comment]
Hi Jipan,

You're right. I've already approved and pushed your changes to the master.

Thanks for your efforts.

**Comment by jipanyang** [comment]
Fix with https://github.com/Azure/sonic-swss/pull/514
