### ISSUE TITLE
Warm reboot:  physical port count may not match configured port count

### ISSUE THREAD

**Issue by jipanyang** [Azure/sonic-swss#567]
On platforms other than BFN_PLATFORM and MLNX_PLATFORM, as of today,  remove port will be skpped and message logged at notice level: 

https://github.com/Azure/sonic-swss/blob/bfce363ef306f45b4dc59f407cb281b8735641c2/orchagent/portsorch.cpp#L1361

When trying warm restart :
the m_portCount got from ASIC won't match that in appDB and cause warm restart failure based on current logic.

https://github.com/Azure/sonic-swss/blob/bfce363ef306f45b4dc59f407cb281b8735641c2/orchagent/portsorch.cpp#L1209

Aug  8 23:15:04.807579 sonic ERR swss/orchagent: :- bake: Invalid port table: m_portCount

Record the issue here for future fix.

**Comment by lguohan** [comment]
if remove_port is not supported in the first place, why m_portCount will deviate from appdb port count?

**Comment by jipanyang** [comment]
This is the current implementation for portorch warm start.
