### ISSUE TITLE
lots of doTask issues that flood the /var/log/syslog

### ISSUE THREAD

**Issue by lguohan** [Azure/sonic-swss#58]
Aug 12 06:38:08 str-s6000-on-1 DEBUG orchagent: :> doTask: enter
Aug 12 06:38:08 str-s6000-on-1 DEBUG orchagent: :< doTask: exit
Aug 12 06:38:08 str-s6000-on-1 DEBUG orchagent: :> doTask: enter
Aug 12 06:38:08 str-s6000-on-1 DEBUG orchagent: :< doTask: exit
Aug 12 06:38:08 str-s6000-on-1 DEBUG orchagent: :> doTask: enter
Aug 12 06:38:08 str-s6000-on-1 DEBUG orchagent: :< doTask: exit
Aug 12 06:38:08 str-s6000-on-1 DEBUG orchagent: :> doTask: enter
Aug 12 06:38:08 str-s6000-on-1 DEBUG orchagent: :< doTask: exit
Aug 12 06:38:08 str-s6000-on-1 DEBUG orchagent: :> doTask: enter

**Comment by stcheng** [comment]
addressed here: https://github.com/Azure/sonic-swss/pull/71
