### ISSUE TITLE
The link of port_config.ini is wrong in swss-schema.md

### ISSUE THREAD

**Issue by sunnogo** [Azure/sonic-swss#6]
[swss-schema.md](https://github.com/Azure/sonic-swss/blob/master/doc/swss-schema.md) shows 'Stores information for physical switch ports managed by the switch chip. device_names are defined in port_config.ini. ', but the link of port_config.init ("https://github.com/stcheng/swss/blob/mock/portsyncd/port_config.ini", 404 not found) is wrong. I think it should be "https://github.com/Azure/sonic-swss/blob/master/portsyncd/port_config.ini".

**Comment by lguohan** [comment]
fixed, thanks.
