### ISSUE TITLE
buffermgrd is flooding syslog with warning messages

### ISSUE THREAD

**Issue by nikos-github** [Azure/sonic-swss#631]
buffermgrd is flooding syslog with the message below at such a high rate that it creates 600 syslog files per day.

Sep 20 21:42:50.923329 sonic-rt-leaf1 WARNING swss#buffermgrd: :- doSpeedUpdateTask: Unable to create/update PG profile for port Ethernet60. Cable length is not set

**Comment by nikos-github** [comment]
@lguohan Please have someone look into this per our discussion.

**Comment by prsunny** [comment]
@nikos-github , @lguohan Is it ok if we just change this to INFO instead of WARN since it is a `retry `logic.

**Comment by nikos-github** [comment]
@prsunny @lguohan Anything that doesn't result in 600 syslog files, is a good start to begin with. The default level is NOTICE so INFO works for me now but it will simply kill everything else if the level is changed to INFO or DEBUG.

Retry logic that constantly and infinitely tries without a backoff mechanism or a timer is just bad code/design. It simply consumes needlessly CPU and resources.
