### ISSUE TITLE
conftest.py not clear DB when test case teardown

### ISSUE THREAD

**Issue by gord1306** [Azure/sonic-swss#829]
Hi, I am trying to the test cases and when I added a new test case in test_vxlan_tunnel.py, I found the entries which were created by the previous test case not clear in Redis DB. Whether the conftest.py need to do the clear operation for DB or restart a new docker-vs container between each test cases

**Comment by stcheng** [comment]
right now each test case will trigger recreating the vs docker - cleaning the database is included. however, it is required for each of the test to clean up afterwards. if you find any tests left some garbage afterwards, please help report/fix it.
