### ISSUE TITLE
More checking for Tunnel mandatory field: ecn/ttl/dscp mode.

### ISSUE THREAD

**Issue by peter-yu** [Azure/sonic-swss#887]
in orchagent/tunneldecaporch.cpp, line: 252
```
  // ttl mode (uniform/pipe)
    attr.id = SAI_TUNNEL_ATTR_DECAP_TTL_MODE;
    if (ttl == "uniform")
    {
        attr.value.s32 = SAI_TUNNEL_TTL_MODE_UNIFORM_MODEL;
    }
    else if (ttl == "pipe")
    {
        attr.value.s32 = SAI_TUNNEL_TTL_MODE_PIPE_MODEL;
    }
    tunnel_attrs.push_back(attr);

    // dscp mode (uniform/pipe)
    attr.id = SAI_TUNNEL_ATTR_DECAP_DSCP_MODE;
    if (dscp == "uniform")
    {
        attr.value.s32 = SAI_TUNNEL_DSCP_MODE_UNIFORM_MODEL;
    }
    else if (dscp == "pipe")
    {
        attr.value.s32 = SAI_TUNNEL_DSCP_MODE_PIPE_MODEL;
    }
    tunnel_attrs.push_back(attr);
```
If the dscp mode is not specified from KeyOpFieldsValuesTuple, the attr.value.s32 will be the previous attr used by ttl mode. If dscp mode is a mandatory field, its existence should be checking inside KeyOpFieldsValuesTuple.  Same as ECN/TTL mode.

**Comment by prsunny** [comment]
As per the https://github.com/Azure/sonic-swss/blob/master/doc/swss-schema.md#tunnel_decap_table, only src_ip field is optional. The rest are mandatory. So this extra check is actually not required. It is presumed that the schema is followed

**Comment by peter-yu** [comment]
Thanks. I will close this issue.
