### ISSUE TITLE
What is the valid prefix of vrf_name? "Vrf" or "vrf"?

### ISSUE THREAD

**Issue by shikenghua** [Azure/sonic-swss#940]
In [VRF HLD](https://github.com/Azure/SONiC/blob/master/doc/sonic-vrf-hld-v1.0.md), it says that vrf_must start with "Vrf". The examples in this document also follow this format.
```
"vrf_name":"Vrf-blue"  // vrf_name must start with "Vrf" prefix
```
But [test_vrf.py](https://github.com/Azure/sonic-swss/blob/master/tests/test_vrf.py) use "vrf" as vrf_name prefix. Currently, sonic-swss doesn't validate vrf_name, so the pytest will still pass.
```
state = vrf_create(asic_db, appl_db, "vrf1",
```
Which one is correct? Thanks.

**Comment by shine4chen** [comment]
test_vrf.py have been refined per VRF HLD requirement. You can find it In [[VRF]: submit vrf feature #392 #943](https://github.com/Azure/sonic-swss/pull/943)

**Comment by shikenghua** [comment]
Got it. Thank you.
